#jinja2:variable_start_string:'<{' , variable_end_string:'}>', block_start_string:'<%', block_end_string:'%>'
- name: Build Docker Compose Files
  gather_facts: no
  vars_prompt:
    - name: 'hosts'
      prompt: 'launch to host'
      private: no
      default: 'localhost'
  hosts: "{{ hosts }}"

  pre_tasks:
    - include_vars: './vars/main.yml'

  tasks:
    - template:
        src: "{{item.src}}"
        dest: "../{{item.dest}}"
        force: yes
      when: "'composefiles' in item.src"
      with_items: "{{project_templates}}"
