#jinja2:variable_start_string:'<{' , variable_end_string:'}>', block_start_string:'<%', block_end_string:'%>'
- name: SETUP DevTools
  vars_prompt:
    - name: 'hosts'
      prompt: 'launch to host'
      private: no
      default: 'localhost'
  hosts: "{{ hosts }}"
  become: yes
  become_user: root

  pre_tasks:
    - include_vars: './vars/aliyun.yml'
    - include_vars: './vars/qiniu.yml'
    - include_vars: './vars/upyun.yml'

  roles:
    - { role: 'qiniutools' }
    - { role: 'osstools' }
    - { role: 'upyuntools' }
