---
#
- name: setup jenkins htpasswd
  htpasswd:
    path: /etc/nginx/site-include.d/jenkins.htpasswd
    name: jenkins
    password: 'abc123456'
    crypt_scheme: md5_crypt
    owner: root
    group: root
    mode: 0644

- name: setup nginx jenkins.conf using auth_base
  lineinfile:
    dest: /etc/nginx/site-enabled/jenkins.conf
    regexp: '# auth_base '
    line: |
      # auth_base
      auth_basic "enter username and password";
      auth_basic_user_file  site-include.d/jenkins.htpasswd;

