- name: create directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ runtime_log_dir }}"
    - "{{ runtime_backup_dir }}"

- name: setup root configuration file
  template:
    src: "nginx/nginx.conf.j2"
    dest: "{{ openresty_install_dir }}/nginx/conf/nginx.conf"

- name: copy conf.d
  copy:
    src: "files/nginx/conf.d"
    dest: "{{ openresty_install_dir }}/nginx/conf/"

- name: setup site-available directory
  file:
    path: "{{ openresty_install_dir }}/nginx/conf/{{ item }}"
    state: directory
  with_items:
    - site-available
    - site-enabled

- name: link configuration files
  file:
    src: "{{ openresty_install_dir }}/nginx/conf"
    dest: "{{ runtime_config_dir }}"
    state: link

- name: clean default configuration files
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ openresty_install_dir }}/nginx/conf/*.default"


- name: setup logrotate
  template:
    src: logrotate.d/nginx.conf.j2
    dest: /etc/logrotate.d/nginx.conf
  tags:
    - logrotate
